/*
    ============================================================
    ORGEE — Phase 6: Customer & Product Analytics
    08_feature_prioritization.sql
    ============================================================

    BUSINESS QUESTION
    Of everything Phases 4-6 have surfaced, what should the
    business actually work on first — ranked by real reach and
    real revenue-at-stake, not by which metric looks worst?

    METHODOLOGY
    Each candidate opportunity below is backed by an actual number
    pulled from the warehouse (reach = customers/sessions affected;
    revenue = dollar value tied to the opportunity), not an assumed
    or fabricated impact score.

    FIXES APPLIED POST-REVIEW:
    1. The "At-Risk retention" opportunity previously used an ad-hoc
       definition (2+ orders, last order >180 days before the
       dataset's max date) that did NOT match the actual RFM
       "At Risk" segment defined in 01/02/04/11
       (f_score >= 3 AND r_score <= 2). A first fix applied the raw
       f_score/r_score condition directly, but that was STILL wrong
       (produced 992 customers / $24,705.66) — it ignored that the
       real segment CASE has branch precedence: some customers
       matching f_score >= 3 AND r_score <= 2 are actually claimed
       by an EARLIER branch first (e.g. "Loyal Customers", when
       m_score >= 3 too), so the raw condition in isolation is
       broader than the true segment. Fixed properly: the full
       segmentation CASE (identical precedence to 01/02/04/11) is
       now applied first, and only THEN filtered to
       segment = 'At Risk' — reconciles exactly to 116 customers /
       $5,668.40, matching 04 and 09.
    2. Revenue scoring: NTILE(5) was previously computed across ALL
       5 opportunities including the ones with NULL revenue, which
       (since NULLs sort first in ASC order) silently consumed the
       low buckets and left only buckets 3-5 for the two opportunities
       that actually have quantified revenue — producing a
       misleadingly narrow 3-5 spread rather than a real ranking.
       Fixed: revenue is now ranked ONLY among opportunities with a
       non-NULL revenue_at_stake (via a separate RANK() over the
       filtered subset, offset above the neutral score), so
       revenue-quantified opportunities are compared only against
       each other, and NULL-revenue opportunities get an explicit,
       separate neutral score of 3.
    3. The "revenue concentration risk" opportunity's reach was
       COUNT(*) FROM Dim_Customer (99,441 — ALL customers, including
       ones who never purchased), and revenue_at_stake was
       SUM(all delivered revenue) * 0.4114 — a hardcoded percentage
       carried over from Phase 4's finding, not computed directly.
       Fixed: both reach and revenue_at_stake now come from the
       same directly-computed top-10%-by-revenue customer
       population (via PERCENT_RANK(), materialized once in
       #Phase8Top10) — the actual SUM(price) generated by those
       specific 9,357 customers, not an indirect approximation.

    TECHNIQUES USED
    UNION ALL, CTE, NTILE, RANK, window functions.
    ============================================================
*/

IF OBJECT_ID('tempdb..#Phase8AtRisk') IS NOT NULL DROP TABLE #Phase8AtRisk;

WITH SnapshotDate AS (
    SELECT MAX(d.full_date) AS snapshot_date
    FROM dbo.Fact_Order_Items foi
    JOIN dbo.Dim_Date d ON foi.order_purchase_date_sk = d.date_sk
    WHERE foi.order_status = 'delivered'
),
CustomerRFMBase AS (
    SELECT
        dc.customer_unique_id,
        COUNT(DISTINCT foi.order_id) AS frequency,
        SUM(foi.price) AS monetary,
        DATEDIFF(DAY, MAX(d.full_date), (SELECT snapshot_date FROM SnapshotDate)) AS recency_days
    FROM dbo.Fact_Order_Items foi
    JOIN dbo.Dim_Customer dc ON foi.customer_sk = dc.customer_sk
    JOIN dbo.Dim_Date d ON foi.order_purchase_date_sk = d.date_sk
    WHERE foi.order_status = 'delivered'
    GROUP BY dc.customer_unique_id
),
CustomerRFMScored AS (
    SELECT
        customer_unique_id, recency_days, frequency, monetary,
        NTILE(5) OVER (ORDER BY recency_days DESC, customer_unique_id ASC) AS r_score,
        CASE
            WHEN frequency = 1 THEN 1 WHEN frequency = 2 THEN 3
            WHEN frequency BETWEEN 3 AND 4 THEN 4 WHEN frequency >= 5 THEN 5
        END AS f_score,
        NTILE(5) OVER (ORDER BY monetary ASC, customer_unique_id ASC) AS m_score
    FROM CustomerRFMBase
),
CustomerSegmented AS (
    SELECT
        customer_unique_id, monetary,
        CASE
            WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4 THEN 'Champions'
            WHEN f_score >= 3 AND m_score >= 3 THEN 'Loyal Customers'
            WHEN f_score = 1 AND r_score >= 4 AND m_score >= 3 THEN 'Potential Loyalists'
            WHEN f_score = 1 AND r_score >= 4 AND m_score < 3 THEN 'New Customers'
            WHEN f_score >= 3 AND r_score <= 2 THEN 'At Risk'
            WHEN r_score <= 2 AND f_score = 1 AND m_score <= 2 THEN 'Lost Customers'
            ELSE 'Needs Attention'
        END AS segment
    FROM CustomerRFMScored
)
SELECT customer_unique_id, monetary
INTO #Phase8AtRisk
FROM CustomerSegmented
WHERE segment = 'At Risk';
-- ^ full segmentation CASE applied first (identical branch
-- precedence to 01/02/04/11), THEN filtered to segment = 'At Risk'
-- — not the raw f_score/r_score condition in isolation, which
-- would wrongly include customers an earlier branch (e.g. "Loyal
-- Customers", when m_score >= 3 too) already claims first.

IF OBJECT_ID('tempdb..#Phase8Top10') IS NOT NULL DROP TABLE #Phase8Top10;

;WITH CustomerRevenue AS (
    SELECT
        dc.customer_unique_id,
        SUM(foi.price) AS monetary
    FROM dbo.Fact_Order_Items foi
    JOIN dbo.Dim_Customer dc ON foi.customer_sk = dc.customer_sk
    WHERE foi.order_status = 'delivered'
    GROUP BY dc.customer_unique_id
),
Ranked AS (
    SELECT
        customer_unique_id, monetary,
        PERCENT_RANK() OVER (ORDER BY monetary DESC) AS pct_rank
    FROM CustomerRevenue
)
SELECT customer_unique_id, monetary
INTO #Phase8Top10
FROM Ranked
WHERE pct_rank <= 0.10;
-- ^ FIX: revenue_at_stake for this opportunity was previously
-- SUM(all delivered revenue) * 0.4114 — a hardcoded percentage
-- carried over from Phase 4's finding, not computed directly from
-- this population. Both reach AND revenue_at_stake below now come
-- from this SAME ranked top-10% population, computed once here —
-- the actual SUM(price) generated by these specific customers,
-- not an indirect approximation.

WITH Opportunities AS (

    SELECT
        'Improve Product View to Add to Cart' AS opportunity,
        'Funnel / UX' AS category,
        (SELECT COUNT(DISTINCT session_id) FROM dbo.Fact_Events WHERE event_type = 'product_view') AS reach,
        CAST(NULL AS DECIMAL(12,2)) AS revenue_at_stake,
        'Phase 5: largest single drop-off (62.76%), 254,621 sessions lost' AS evidence

    UNION ALL

    SELECT
        'Reduce Cart Abandonment (Add to Cart to Checkout)',
        'Funnel / UX',
        (SELECT COUNT(DISTINCT session_id) FROM dbo.Fact_Events WHERE event_type = 'add_to_cart'),
        NULL,
        'Phase 5: 45.90% cart abandonment rate, 69,342 sessions'

    UNION ALL

    SELECT
        'Retention program for At-Risk high-value customers',
        'Customer',
        (SELECT COUNT(*) FROM #Phase8AtRisk),
        (SELECT SUM(monetary) FROM #Phase8AtRisk),
        'Phase 6: the actual RFM At-Risk segment (f_score >= 3, r_score <= 2) — same group as 02/04/11, not a broader heuristic'

    UNION ALL

    SELECT
        'Improve search prominence / discoverability',
        'Funnel / UX',
        (SELECT COUNT(DISTINCT session_id) FROM dbo.Fact_Events WHERE event_type = 'session_start'),
        NULL,
        'Phase 5: searching sessions convert at 11.21% vs 5.60% for non-searchers'

    UNION ALL

    SELECT
        'Grow revenue concentration risk — top 10% customer dependency',
        'Customer',
        (SELECT COUNT(*) FROM #Phase8Top10),
        (SELECT SUM(monetary) FROM #Phase8Top10),
        'Phase 4: top 10% of customers generate 41.14% of total revenue'
),
RevenueRanked AS (
    -- Rank ONLY the opportunities that have a real, quantified
    -- revenue_at_stake — NULL-revenue opportunities are excluded
    -- from this ranking entirely and scored separately below.
    SELECT
        opportunity,
        3 + RANK() OVER (ORDER BY revenue_at_stake ASC) AS revenue_score
    FROM Opportunities
    WHERE revenue_at_stake IS NOT NULL
),
Scored AS (
    SELECT
        o.opportunity, o.category, o.reach, o.revenue_at_stake, o.evidence,
        NTILE(5) OVER (ORDER BY o.reach ASC) AS reach_score,
        COALESCE(rr.revenue_score, 3) AS revenue_score
        -- NULL-revenue opportunities get an explicit neutral score of 3,
        -- separate from and never competing against the revenue ranking above
    FROM Opportunities o
    LEFT JOIN RevenueRanked rr ON o.opportunity = rr.opportunity
)
SELECT
    opportunity,
    category,
    reach,
    revenue_at_stake,
    reach_score,
    revenue_score,
    (reach_score + revenue_score) AS priority_score,
    RANK() OVER (ORDER BY (reach_score + revenue_score) DESC) AS priority_rank,
    evidence
FROM Scored
ORDER BY priority_rank;

/*
    BUSINESS INTERPRETATION — fill in after running:
    - Which opportunity ranks #1 once both reach AND revenue are
      considered together, not just the loudest single metric?

    BUSINESS IMPLICATION — fill in after running:
    - This ranking is the direct input to 09_product_recommendations.sql

    NOTE: the revenue_score formula (3 + RANK()) is scaled for the
    current fixed set of exactly 2 revenue-quantified opportunities
    (producing scores 4 and 5). If more revenue-quantified
    opportunities are added later, this offset would need
    generalizing (e.g. NTILE among the non-NULL subset, rescaled
    into the 4-5 range) rather than growing unbounded past 5.
*/

DROP TABLE #Phase8AtRisk;
DROP TABLE #Phase8Top10;
